# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 030b8de7781a0a18c792c2eef7c5a48bf2e60385d25f749a94bb13303389993979d68fc136c3c588d2d247a27ec9ceb18005f27c7f1bf51d0fb62a1068a66665

test:
  secret_key_base: 4517bcedbf53ba25d418c59fd43637a6e4c2631f7696cb12ca1e4c608c0500105c67bff0616c0dd8a8cf1ccc1b4ae6bac4f133fa1a6fec68ee3b5fbe04edb11a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
